### ISSUE TITLE
galaxy.yml required

### ISSUE THREAD

**Issue by jgroom33** [ansible-collections/vmware_rest_code_generator#2]
##### SUMMARY

galaxy.yml file is required

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
2.9.11
```

##### STEPS TO REPRODUCE

`tox -e refresh_modules`

##### EXPECTED RESULTS

success

##### ACTUAL RESULTS

```paste below
FileNotFoundError: [Errno 2] No such file or directory: 'vmware_rest/galaxy.yml'
ERROR: InvocationError: '/home/jgroom/src/vmware_rest_code_generator/refresh_modules.py'
```

**Comment by goneri** [comment]
The `galaxy.yml` file is here: https://github.com/ansible-collections/vmware_rest/blob/main/galaxy.yml I don't generate it with these scripts.
