### ISSUE TITLE
use Jinja templates

### ISSUE THREAD

**Issue by jgroom33** [ansible-collections/vmware_rest_code_generator#38]
##### SUMMARY
The code is challenging to read.  Use Jinja templates instead of multiline strings.

##### ISSUE TYPE
- Feature Idea

**Comment by goneri** [comment]
Hi @jgroom33,

I agree on this. I'm not sure yet if we can just use standard f-string (https://www.python.org/dev/peps/pep-0498/) or if we need something more powerful like Jinja2. I would also like to remove astunparse.
